p1 = Project.create(name: "Apache Webs", description: "Erstellen einer Website zur Einrichtung neuer Webs", start_date: "2013-02-01")
p2 = Project.create(name: "Pruefungsvorbereitung", description: "Vorbereitung der Abschlusspruefungen", start_date: "2013-03-01")
p3 = Project.create(name: "Abschlussarbeit", description: "Erstellen eines Projekts fuer den Technikerabschluss", start_date: "2012-10-01")
Iteration.create(name: "Layout", description: "Erstellen eines Seiten-layouts", start_date: "2013-02-01", end_date: "2013-02-02", project_id: p1.id)
Iteration.create(name: "Login", description: "Erstellen eines Logins", start_date: "2013-03-01", end_date: "2013-04-02", project_id: Project.first.id)
Group.create(name: "admin", description: "Admin Group")
Group.create(name: "management", description: "Projektleiter")
Group.create(name: "member", description: "Projektteilnehmer")
User.create(name: "admin",email: "admin@gmx.de", password: "password", group_id: 1,project_id: 0)
User.create(name: "peter",email: "peter@gmx.de", password: "password", group_id: 2,project_id: p1.id)
User.create(name: "theo",email: "theo@gmx.de", password: "password", group_id: 3,project_id: p1.id)
User.create(name: "birte",email: "birte@gmx.de", password: "password", group_id: 3,project_id: p1.id)
User.create(name: "test",email: "test@gmx.de", password: "password", group_id: 3,project_id: p2.id)